USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS EYADC;
CREATE SCHEMA IF NOT EXISTS EYADC.REPO;
USE DATABASE EYADC;
USE SCHEMA REPO;

CREATE OR REPLACE TASK AUTO_FETCH_GIT
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON */5 * * * * UTC'
AS
  ALTER GIT REPOSITORY EYADC.REPO.EY_AI_DATA_CHALLENGE FETCH;

-- Enable the task
ALTER TASK AUTO_FETCH_GIT REEYADC.PUBLIC.AUTO_FETCH_GITSUME;

-- Verify existance
SHOW TASKS IN SCHEMA EYADC.REPO;

SHOW TASKS LIKE 'AUTO_FETCH_GIT';

LIST @EYADC.REPO.EY_AI_DATA_CHALLENGE/branches/main/;