
USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS EYADC;
CREATE SCHEMA IF NOT EXISTS EYADC.INTEGRATIONS;
CREATE SCHEMA IF NOT EXISTS EYADC.REPO;

USE DATABASE EYADC;
USE SCHEMA INTEGRATIONS;
USE SCHEMA REPO;

CREATE OR REPLACE SECRET EYADC.INTEGRATIONS.GH_PAT
  TYPE = PASSWORD
  USERNAME = 'tomassantos484'
  PASSWORD = '<YOUR_GITHUB_PAT>';

CREATE OR REPLACE API INTEGRATION EY_GITHUB_API_INT
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/tomassantos484')
  ALLOWED_AUTHENTICATION_SECRETS = (EYADC.INTEGRATIONS.GH_PAT)
  ENABLED = TRUE;

CREATE OR REPLACE GIT REPOSITORY EYADC.REPO.EY_AI_DATA_CHALLENGE
  API_INTEGRATION = EY_GITHUB_API_INT
  GIT_CREDENTIALS = EYADC.INTEGRATIONS.GH_PAT
  ORIGIN = 'https://github.com/tomassantos484/ey-ai-data-challenge.git';

ALTER GIT REPOSITORY EYADC.REPO.EY_AI_DATA_CHALLENGE FETCH;
SHOW API INTEGRATIONS LIKE 'EY_GITHUB_API_INT';
SHOW SECRETS IN SCHEMA EYADC.INTEGRATIONS;
SHOW GIT REPOSITORIES IN SCHEMA EYADC.REPO;