
USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS EYADC;
CREATE SCHEMA IF NOT EXISTS EYADC.INTEGRATIONS;
CREATE SCHEMA IF NOT EXISTS EYADC.REPO;

USE DATABASE EYADC;
USE SCHEMA INTEGRATIONS;

CREATE OR REPLACE SECRET EYADC.INTEGRATIONS.TOMAS_GH_PAT
  TYPE = PASSWORD
  USERNAME = 'tomassantos484'
  PASSWORD = '<TOMAS_PAT_HERE>';

CREATE OR REPLACE SECRET EYADC.INTEGRATIONS.LR_PAT
  TYPE = PASSWORD
  USERNAME = '1aur'
  PASSWORD = '<LR_PAT_HERE>';

CREATE OR REPLACE API INTEGRATION EY_GITHUB_API_INT
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/tomassantos484')
  ALLOWED_AUTHENTICATION_SECRETS = (
    EYADC.INTEGRATIONS.TOMAS_GH_PAT,
    EYADC.INTEGRATIONS.LR_PAT
  )
  ENABLED = TRUE;


CREATE OR REPLACE GIT REPOSITORY EYADC.REPO.EY_AI_DATA_CHALLENGE
  API_INTEGRATION = EY_GITHUB_API_INT
  GIT_CREDENTIALS = EYADC.INTEGRATIONS.GH_PAT
  ORIGIN = 'https://github.com/tomassantos484/ey-ai-data-challenge.git';

ALTER GIT REPOSITORY EYADC.REPO.EY_AI_DATA_CHALLENGE FETCH;

SHOW API INTEGRATIONS LIKE 'EY_GITHUB_API_INT';
SHOW SECRETS IN SCHEMA EYADC.INTEGRATIONS;
SHOW GIT REPOSITORIES IN SCHEMA EYADC.REPO;


CREATE NETWORK RULE IF NOT EXISTS PYPI_NETWORK_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = (
    'pypi.org',
    'pypi.python.org',
    'pythonhosted.org',
    'files.pythonhosted.org'
  );

CREATE NETWORK RULE IF NOT EXISTS PLANETARY_COMPUTER_NETWORK_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = (
    'planetarycomputer.microsoft.com',
    'api.planetarycomputer.microsoft.com',
    'planetarycomputer.microsoft.com:443',
    'api.stacspec.org',
    'stacspec.org',
    'planetarycomputer.blob.core.windows.net',
    'cpdataeuwest.blob.core.windows.net',
    'ai4edataeuwest.blob.core.windows.net',
    'naipeuwest.blob.core.windows.net',
    'planetarycomputer.dfs.core.windows.net',
    'cpdataeuwest.dfs.core.windows.net',
    '*.blob.core.windows.net',
    '*.dfs.core.windows.net',
    'login.microsoftonline.com',
    'management.azure.com'
  );

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION DATA_CHALLENGE_EXTERNAL_ACCESS
  ALLOWED_NETWORK_RULES = (
    EYADC.INTEGRATIONS.PYPI_NETWORK_RULE,
    EYADC.INTEGRATIONS.PLANETARY_COMPUTER_NETWORK_RULE
  )
  ENABLED = TRUE;

SHOW NETWORK RULES IN SCHEMA EYADC.INTEGRATIONS;
DESCRIBE INTEGRATION DATA_CHALLENGE_EXTERNAL_ACCESS;